name: Terraform Change PR Commenter
description: Parse changes from Terraform Plan JSON and post them for PR review
inputs:
  json-file:
    description: File location for the Terraform Plan JSON file
    required: false
    default: tfplan.json
  github-token:
    description: GitHub Token
    required: false
    default: '${{github.token}}'
runs:
  using: node16
  main: dist/index.js
