apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # Component names should be simple and URL-friendly
  name: terraform-change-pr-commenter
  description: >-
    GitHub Action that parses Terraform plan JSON files, summarizes the changes,
    and posts concise comments (and optional workflow summaries) to pull requests.

  # Annotations — see https://backstage.io/docs/features/software-catalog/well-known-annotations
  annotations:
    github.com/project-slug: liatrio/terraform-change-pr-commenter

  tags:
    - javascript
    - terraform
    - github-action
    - ci
    - iac

  links:
    - url: https://github.com/liatrio/terraform-change-pr-commenter
      title: Source Repository
      icon: github
    - url: https://github.com/marketplace/actions/terraform-change-pr-commenter
      title: GitHub Marketplace Listing
      icon: marketplace


spec:
  # component category, e.g. service, library, tool, website …
  type: library
  # Review lifecycle and pick one of the three that make the most sense.
  # https://backstage.io/docs/features/software-catalog/descriptor-format/#speclifecycle-required
  lifecycle: production
  owner: platform-engineering
  system: developer-platform
  dependsOn: []
  consumesApis: []
  providesApis: []

