on:
  push:
    branches:
      - 'step-id-link-test'
      
jobs:
  get-step-link:
    runs-on: ubuntu-latest

    steps:
      - name: context info print
        run: echo The username is ${{ inputs.username }}
        run: echo http://${{ GITHUB_REPOSITORY }}/runs/${{ GITHUB_RUN_ID }}
