on:
  push:
    branches:
      - 'step-id-link-test'
      
jobs:
  get-step-link:
    runs-on: ubuntu-latest

    steps:
      - name: user info print
        run: echo The username is ${{ inputs.username }}
      - name: context url
        run: echo http://${{ env.GITHUB_REPOSITORY }}/runs/${{ env.GITHUB_RUN_ID }}
