name: Reusable Terraform Test Workflow

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      test-mode:
        description: 'Test mode for reusable workflow'
        required: false
        type: string
        default: 'reusable'

jobs:
  reusable-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn install
      - run: yarn run build

      - name: Test PR Commenter via workflow_call
        uses: ./
        with:
          json-file: test-data/tf_test.json
          comment-header: "Terraform Plan via Reusable Workflow (workflow_call event)"
          expand-comment: "true"
          include-workflow-link: "true"
          include-job-link: "true"